apiVersion: apps/v1
kind: Deployment
metadata:
  name: khagu-dev-front
  namespace: default
  labels:
    app: khagu-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khagu-dev-front
  template:
    metadata:
      labels:
        app: khagu-dev-front
    spec:
      containers:
        - name: khagu-dev-front
          image: "europe-west1-docker.pkg.dev/khagu-devops/khagu-dev-images-registry/khagu-dev-front:1.1.8.4" # Remplacer par votre repo
          ports:
            - containerPort: 80
            - containerPort: 7000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "khagu-dev-front-hpa"
  namespace: default
  labels:
    app: "khagu-dev-front"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "khagu-dev-front"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: khagu-dev-front
  namespace: default
spec:
  type: NodePort
  selector:
    app: khagu-dev-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: khagu-dev-https-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: www.projet.khagu-dev.fr
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: back-service
            port:
              number: 7000
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: khagu-dev-front
            port:
              number: 80