apiVersion: apps/v1
kind: Deployment
metadata:
  name: khagu-dev-front
  namespace: default
  labels:
    app: khagu-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khagu-dev-front
  template:
    metadata:
      labels:
        app: khagu-dev-front
    spec:
      containers:
        - name: khagu-dev-front
          image: "europe-west1-docker.pkg.dev/khagu-dev-411510/khagu-dev-images-registry/khagu-dev-front:1.0.6" # Remplacer par votre repo
          ports:
            - containerPort: 80
            - containerPort: 7000
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "khagu-dev-front-hpa"
  namespace: "default"
  labels:
    app: "khagu-dev-front"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "khagu-dev-front"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: khagu-dev-front
spec:
  type: LoadBalancer
  selector:
    app: khagu-dev-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: khagu-dev-front-to-back
spec:
  type: ClusterIP
  selector:
    app: khagu-dev-front
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
