apiVersion: apps/v1 # Version de l'API
kind: Deployment # Type de ressource
metadata: # Métadonnées
  name: khagu-dev-back # Nom de la ressource
  namespace: default # Espace de nom
  labels: # Labels
    app: khagu-dev # Nom de l'application
spec: # Spécification
  replicas: 1 # Nombre de réplicas
  selector: # Sélecteur
    matchLabels: # Labels de correspondance 
      app: khagu-dev-back # Nom de l'application du pod
  template: # Modèle de déploiement des pods
    metadata: # Métadonnées du modèle
      labels: # Labels de correspondance
        app: khagu-dev-back # Nom de l'application du pod
    spec: # Spécification du pod
      containers: # Conteneurs du pod
        - name: khagu-dev-back # Nom du conteneu
          image: "europe-west1-docker.pkg.dev/khagu-devops/khagu-dev-images-registry/khagu-dev-back:1.0.9.8" # Image du conteneur
          ports: # Ports du conteneur
            - containerPort: 7000 # Port du conteneur 
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "khagu-dev-back-hpa"
  namespace: default
  labels:
    app: "khagu-dev-back"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "khagu-dev-back"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  healthCheck:
    requestPath: /health
    port: 7000
    type: HTTP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"7000":"my-backendconfig"}}'
  name: back-service
spec:
  selector:
    app: khagu-dev-back
  ports:
  - port: 7000
    targetPort: 7000