apiVersion: apps/v1
kind: Deployment
metadata:
  name: khagu-dev-back
  namespace: default
  labels:
    app: khagu-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khagu-dev-back
  template:
    metadata:
      labels:
        app: khagu-dev-back
    spec:
      containers:
        - name: khagu-dev-back
          image: "europe-west1-docker.pkg.dev/khagu-dev-411510/khagu-dev-images-registry/khagu-dev-back:1.0.3" # Remplacer par votre repo
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    app: khagu-dev-back
  type: LoadBalancer
  ports:
    - port: 7000
      targetPort: 7000
