name: CI

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  DB_USER_PASS: ${{ secrets.MONGO_USERNAME }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install front dependencies
        run: cd client && npm ci

      - name: Install back dependencies
        run: cd server && npm ci

      - name: create env file
        run: |
          cd ./server/config
          echo DB_USER_PASS=$MONGO_USERNAME >> .env

      - name: Run back tests
        run: cd server && npm test

      - name: run back server
        run: cd server && npm run watch

      - name: Run front tests
        run: cd client && npm test

      - name: Build Docker images and push to Docker Hub
        if: ${{ success() }}
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker build -t khagu/khagu-dev-front ./client
          docker push khagu/khagu-dev-front
          docker build -t khagu/khagu-dev-back ./server
          docker push khagu/khagu-dev-back
